"""add qr

Revision ID: 5a557586bb7a
Revises: 0d15525fa80c
Create Date: 2023-05-23 13:40:49.185361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a557586bb7a'
down_revision = '0d15525fa80c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('qr_code_url', sa.String(length=255), nullable=True))
    op.add_column('images', sa.Column('public_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'images', ['public_id'])
    op.create_unique_constraint(None, 'images', ['qr_code_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'public_id')
    op.drop_column('images', 'qr_code_url')
    # ### end Alembic commands ###
