"""fix users

Revision ID: a84236409f10
Revises: 3d401fcfcbb2
Create Date: 2023-05-17 20:55:10.500900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84236409f10'
down_revision = '3d401fcfcbb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
