"""add_item_tag_rel

Revision ID: e9d4f7e86704
Revises: 5a557586bb7a
Create Date: 2023-05-23 15:12:37.938066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d4f7e86704'
down_revision = '5a557586bb7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'public_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('tags_images_tag_id_fkey', 'tags_images', type_='foreignkey')
    op.drop_constraint('tags_images_image_id_fkey', 'tags_images', type_='foreignkey')
    op.create_foreign_key(None, 'tags_images', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_images', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_images', type_='foreignkey')
    op.drop_constraint(None, 'tags_images', type_='foreignkey')
    op.create_foreign_key('tags_images_image_id_fkey', 'tags_images', 'images', ['image_id'], ['id'])
    op.create_foreign_key('tags_images_tag_id_fkey', 'tags_images', 'tags', ['tag_id'], ['id'])
    op.alter_column('images', 'public_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
